### ISSUE TITLE
FuzzyOpen not working in a git repo

### ISSUE THREAD

**Issue by afnanenayet** [cloudhead/neovim-fuzzy#42]
Whenever I call FuzzyOpen in a directory that's under a git repository, it yields an error:

```
Error detected while processing function <SNR>70_fuzzy_open:                                                                                                   
line    2:                                                                                                                                                     
E344: Can't find directory "^[[1 q/home/afnan/dev/gfx_research/sampleview" in cdpath                                                                           
E472: Command failed  
```

This seems to only occur in git repositories, or subfolders under a git repository. FuzzyGrep is not affected. If this is relevant, I'm running Linux 4.19.11.

**Comment by jf** [comment]
For the record I do *not* have this problem at all. Does anybody else have this problem? I was almost tempted to not try this because of this report, but I'm glad I did. I have no problem.

neovim-fuzzy version: https://github.com/cloudhead/neovim-fuzzy/commit/53383395befafce802c902c21b54847074454491
fzy version: 1.0

**Comment by cloudhead** [comment]
Yeah I've never seen this and know a bunch of people using the plugin.

It also looks like something weird is happening here: `"^[[1 q/home/afnan/dev/gfx_research/sampleview"`, it looks like an escape sequence before the path.

I'm going to close this since it's a year old and no one else has reported the issue and have no idea what could be wrong..
